### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ucalyptus** [belskikh/kekas#18]
sayantan@kali:~$ sudo pip3 install kekas
Collecting kekas
  Using cached https://files.pythonhosted.org/packages/2d/04/4487855bbc12532d54729b1bf07531c8b69202981fa69561a983e234220d/kekas-0.1.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6wp28_se/kekas/setup.py", line 3, in <module>
        import kekas
      File "/tmp/pip-install-6wp28_se/kekas/kekas/__init__.py", line 1, in <module>
        from .keker import Keker
      File "/tmp/pip-install-6wp28_se/kekas/kekas/keker.py", line 12, in <module>
        from .callbacks import Callback, Callbacks, ProgressBarCallback, \
      File "/tmp/pip-install-6wp28_se/kekas/kekas/callbacks.py", line 14, in <module>
        from tensorboardX import SummaryWriter
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/__init__.py", line 5, in <module>
        from .torchvis import TorchVis
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/torchvis.py", line 11, in <module>
        from .writer import SummaryWriter
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 27, in <module>
        from .event_file_writer import EventFileWriter
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/event_file_writer.py", line 28, in <module>
        from .proto import event_pb2
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/proto/event_pb2.py", line 15, in <module>
        from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/proto/summary_pb2.py", line 15, in <module>
        from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/proto/tensor_pb2.py", line 15, in <module>
        from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
      File "/usr/local/lib/python3.6/dist-packages/tensorboardX/proto/resource_handle_pb2.py", line 22, in <module>
        serialized_pb=_b('\n(tensorboardX/proto/resource_handle.proto\x12\x0ctensorboardX\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
    TypeError: __new__() got an unexpected keyword argument 'serialized_options'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6wp28_se/kekas/
sayantan@kali:~$

**Comment by belskikh** [comment]
Can't replicate this bug.
You can try `sudo pip3 install --user kekas` , it usually helps in such situations

**Comment by ucalyptus** [comment]
Thanks, done!
